name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install latexmk texlive-latex-base texlive-latex-recommended texlive-lang-german texlive-fonts-extra texlive-luatex
    - name: Build the paper with latexmk
      run: |
        cd paper; latexmk
        echo Add other actions to build,
        echo test, and deploy your project.
