name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install latexmk texlive-latex-base texlive-latex-recommended texlive-lang-german texlive-fonts-extra texlive-luatex texlive-xetex
    - name: Build the paper with latexmk
      run: |
        cd paper; latexmk
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Upload the paper
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: paper/strace.pdf
